name: Scheduled Tweets

on:
  schedule:
    - cron: "0 2 * * *"   # 09:00 ICT
    - cron: "0 8 * * *"   # 15:00 ICT
    - cron: "0 14 * * *"  # 21:00 ICT
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install -r requirements.txt
      - name: Post one tweet
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: python post_now.py
